
BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: '34'
            font_size: 40
            on_text: app.handle_calculation()

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
                on_press: app.handle_direction(1)
            Button:
                text: 'Down'
                on_press: app.handle_direction(-1)

    Button:
        text: 'Convert M to Km'
        on_press: app.handle_calculation()

    Label:
        id: output_label
        text: '54.71756'
        font_size: 40
        colour: (1, 1, 0, 1)
